// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;

namespace MonoDevelop.Mac.Debug
{
	[Register ("DebugWindow")]
	public class DebugWindow : NSWindow
	{
		// Called when created from unmanaged code
		public DebugWindow (IntPtr handle) : base (handle)
		{
			InspectorContext.Attach (this);
		}

		public override bool MakeFirstResponder (NSResponder aResponder)
		{
			InspectorContext.ChangeFocusedView(aResponder as NSView);
			return base.MakeFirstResponder (aResponder);
		}
	}
}
