// This file has been autogenerated from a class added in the UI designer.

using System.Collections.Generic;
using AppKit;
using MonoDevelop.Mac.Debug.Services;

namespace MonoDevelop.Mac.Debug
{
	public interface IInspectDelegate
	{
		void SetFont(IViewWrapper view, NSFont font);
		FontData GetFont(IViewWrapper view);
		void ConvertToNodes(IViewWrapper view, NodeView nodeView);
		ViewWrapper GetWrapper(IViewWrapper viewSelected);
		void Recursively (IViewWrapper contentView, List<DetectedError> DetectedErrors);
	}
}