// This file has been autogenerated from a class added in the UI designer.

using System.Collections.Generic;
using System.Threading.Tasks;
using AppKit;
using MonoDevelop.Mac.Debug.Services;

namespace MonoDevelop.Mac.Debug
{
	public interface IInspectDelegate
	{
		void SetFont(IViewWrapper view, NSFont font);
		FontData GetFont(IViewWrapper view);
		void ConvertToNodes(IViewWrapper view, NodeView nodeView, InspectorViewMode viewMode);
		object GetWrapper (IViewWrapper viewSelected, InspectorViewMode viewMode);
		void Recursively (IViewWrapper contentView, List<DetectedError> DetectedErrors, InspectorViewMode viewMode);
		void RemoveAllErrorWindows(IWindowWrapper windowWrapper);
		Task<Xwt.Drawing.Image> OpenDialogSelectImage(IWindowWrapper selectedWindow);
		void SetButton(NSButton button, Xwt.Drawing.Image image);
		void SetButton(NSImageView imageview, Xwt.Drawing.Image image);
		Task InvokeImageChanged(IViewWrapper view, IWindowWrapper selectedWindow);
		IBorderedWindow CreateErrorWindow (IViewWrapper view);
	}
}