// This file has been autogenerated from a class added in the UI designer.

using CoreGraphics;
using System.Collections.Generic;

namespace MonoDevelop.Mac.Debug
{
	public interface IViewWrapper
	{
		bool Hidden { get; }
		string Identifier { get; }
		CGRect AccessibilityFrame { get; }
		List<IViewWrapper> Subviews { get; }
		IViewWrapper NextValidKeyView { get; }
		IViewWrapper PreviousValidKeyView { get; }
		CGRect Frame { get; }
		IViewWrapper Superview { get; }
		string AccessibilityTitle { get; set; }
		string AccessibilityHelp { get; set; }
		object AccessibilityParent { get; set; }
		bool CanBecomeKeyView { get; }
		object Content { get; }
		void RemoveFromSuperview ();
	}
}
