// This file has been autogenerated from a class added in the UI designer.

using System;

namespace MonoDevelop.Mac.Debug
{
	public interface IWindowWrapper
	{
		IViewWrapper ContentView { get; set; }
		IViewWrapper FirstResponder { get; }

		event EventHandler ResizeRequested;
		event EventHandler MovedRequested;
	}
}
