// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

namespace MonoDevelop.Mac.Debug
{
	class MethodTableViewItem : TableViewItem
	{
		public MethodInfo MethodInfo;

		public MethodTableViewItem(MethodInfo method) : base(method.ToString())
		{
			MethodInfo = method;
		}
	}

	class MethodListView : TableView
	{
		public bool ShowAllMethods { get; set; }
		public void SetObject (object element)
		{
			List<MethodInfo> methodInfos;

			//if (ShowAllMethods)
			//{
			//	methodInfos = element.GetType()
			//			   .GetMethods(BindingFlags.Public | BindingFlags.Instance);
			//}
			//else
			//{
			methodInfos = element.GetType()
			.GetRuntimeMethods()
			.ToList();

			var tableItems = new List<TableViewItem>();
			foreach (var method in methodInfos) {
				tableItems.Add (new MethodTableViewItem(method));
			}
			SetData (tableItems);
		}
	}
}
