// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using AppKit;
using Foundation;

namespace MonoDevelop.Mac.Debug
{
	public class NSFirstResponderWatcher : IDisposable
	{
		NSTimer timer;
		NSResponder responder;
		NSWindow window;
		public EventHandler<NSResponder> Changed;
		public double Interval { get; set; } = 0.2;

		public NSFirstResponderWatcher (NSWindow window)
		{
			this.window = window;
		}

		void TickHandleAction (NSTimer obj)
		{
			if (window.FirstResponder != responder) {
				responder = window.FirstResponder;
				Changed?.Invoke (this, responder);
			}
		}

		public void Start ()
		{
			Stop ();
			timer = NSTimer.CreateRepeatingScheduledTimer (TimeSpan.FromSeconds (Interval), TickHandleAction);
		}

		public void Stop ()
		{
			if (timer != null) {
				timer.Invalidate ();
			}
		}

		public void Dispose ()
		{
			Stop ();
		}
	}
}
