// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Xamarin.PropertyEditing.Mac;
using Xamarin.PropertyEditing.Themes;

namespace MonoDevelop.Mac.Debug
{
	public class ToolbarWindow : NSWindow
	{
		public event EventHandler ShowIssues;
		public event EventHandler ScanForIssues;

		public event EventHandler<bool> KeyViewLoop;
		public event EventHandler<bool> NextKeyViewLoop;
		public event EventHandler<bool> PreviousKeyViewLoop;

		public event EventHandler<bool> ThemeChanged;

		const int MenuItemSeparation = 3;
		const int LeftPadding = 5;

		int issuesFound = 0;

		NSButton errorTextButton;

		NSTextField errorLabel;

		public int IssuesFound
		{
			get => issuesFound;
			set
			{
				issuesFound = value;
				errorLabel.StringValue = $"{value} issues found";
			}
		}

		readonly NSStackView stackView;

		public ToolbarWindow ()
		{
			//BackgroundColor = NSColor.Clear;
			IsOpaque = false;
			StyleMask = NSWindowStyle.Titled | NSWindowStyle.FullSizeContentView;
			TitlebarAppearsTransparent = true;
			TitleVisibility = NSWindowTitleVisibility.Hidden;
			ShowsToolbarButton = false;
			MovableByWindowBackground = false;

			stackView = NativeViewHelpers.CreateHorizontalStackView (MenuItemSeparation);
			ContentView.AddSubview (stackView);
			stackView.CenterYAnchor.ConstraintEqualToAnchor (ContentView.CenterYAnchor, 0).Active = true;
			stackView.LeftAnchor.ConstraintEqualToAnchor (ContentView.LeftAnchor, LeftPadding).Active = true;

			//Visual issues view
			var keyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-actual"));
			Attach (keyViewLoopButton);
			keyViewLoopButton.Activated += (s, e) => {
				KeyViewLoop?.Invoke(this, keyViewLoopButton.IsToggled);
			};

			var prevKeyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-previous"));
			Attach (prevKeyViewLoopButton);
			prevKeyViewLoopButton.Activated += (s, e) => {
				PreviousKeyViewLoop?.Invoke(this, prevKeyViewLoopButton.IsToggled);
			};

			var nextKeyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-next"));
			Attach (nextKeyViewLoopButton);
			nextKeyViewLoopButton.Activated += (s, e) => {
				NextKeyViewLoop?.Invoke(this, nextKeyViewLoopButton.IsToggled);
			};

			stackView.AddArrangedSubview (new VerticalSeparator ());

			var themeButton = new ToggleButton (NSImage.ImageNamed ("style-16"));
			Attach (themeButton);
			themeButton.Activated += ThemeButton_Activated;

			stackView.AddArrangedSubview(new VerticalSeparator());

			errorTextButton = new ToggleButton (NSImage.ImageNamed("error-16"));
			Attach (errorTextButton);
			errorTextButton.Activated += ErrorTextButton_Activated;

			var rescanButton = new ImageButton(NSImage.ImageNamed("rescan-16"));
			Attach (rescanButton);
			rescanButton.Activated += RescanButton_Activated;

			stackView.AddArrangedSubview(new VerticalSeparator());

			errorLabel = NativeViewHelpers.CreateLabel ($"{IssuesFound} issues");
			stackView.AddArrangedSubview(errorLabel);
		}

		void ThemeButton_Activated (object sender, EventArgs e)
		{
			if (sender is ToggleButton btn) {
				ThemeChanged?.Invoke (this, btn.IsToggled);
			}
		}

		void Attach (NSView view)
		{
			stackView.AddArrangedSubview (view);
			view.WidthAnchor.ConstraintEqualToConstant (StatusWindow.ButtonWidth).Active = true;
		}

		void RescanButton_Activated(object sender, EventArgs e)
		{
			ScanForIssues?.Invoke(this, EventArgs.Empty);
		}

		void ErrorTextButton_Activated(object sender, EventArgs e)
		{
			ShowIssues?.Invoke(this, EventArgs.Empty);
		}

		protected override void Dispose(bool disposing)
		{
			errorTextButton.Activated -= ErrorTextButton_Activated;
			base.Dispose(disposing);
		
		}
	}
}
