// This file has been autogenerated from a class added in the UI designer.

using System.Collections.Generic;
using AppKit;

namespace MonoDevelop.Mac.Debug
{
	public static class ViewDebuggerContext
	{
		static readonly Dictionary<NSWindow, ViewDebugDelegate> items;
		static ViewDebuggerContext ()
		{
			items = new Dictionary<NSWindow, ViewDebugDelegate> ();
		}

		public static void Attach (NSWindow window) 
		{
			if (!items.ContainsKey (window)) {
				items.Add (window, new ViewDebugDelegate (window));
			}
		}

		public static void Remove (NSWindow window)
		{
			ViewDebugDelegate selected;
			if (items.TryGetValue (window,out selected)) {
				selected.Dispose ();
				items.Remove (window);
			}
		}
	}
}
