// This file has been autogenerated from a class added in the UI designer.


using AppKit;

namespace MonoDevelop.Mac.Debug
{
	class ImageButton : NSButton
	{
		bool isPressed;
		public ImageButton(NSImage image)
		{
			Bordered = true;
			BezelStyle = NSBezelStyle.Rounded;
			Title = "";
			Image = image;
			ImageScaling = NSImageScale.AxesIndependently;
			TranslatesAutoresizingMaskIntoConstraints = false;
		}

		public bool Visible {
			get => !Hidden;
			set => Hidden = !value;
		}
	}
}
