// This file has been autogenerated from a class added in the UI designer.


using System;
using AppKit;
using Foundation;

namespace MonoDevelop.Mac.Debug
{
	class ToggleButton : NSButton
	{
		public event EventHandler Toggled;

		public override void MouseDown(NSEvent theEvent)
		{
			base.MouseDown(theEvent);
			Toggled?.Invoke(this, EventArgs.Empty);
		}

		public override void PerformClick (NSObject sender)
		{
			base.PerformClick(sender);
			Toggled?.Invoke(this, EventArgs.Empty);
		}

		public bool IsToggled
		{
			get => State == NSCellStateValue.On;
			set
			{
				if (IsToggled == value)
				{
					return;
				}
				State = value ? NSCellStateValue.On : NSCellStateValue.Off;
				Toggled?.Invoke(this, EventArgs.Empty);
			}
		}

		public ToggleButton(NSImage image)
		{
			Bordered = true;
			BezelStyle = NSBezelStyle.Rounded;
			Title = "";
			SetButtonType(NSButtonType.OnOff);
			Image = image;
			ImageScaling = NSImageScale.AxesIndependently;
			TranslatesAutoresizingMaskIntoConstraints = false;
		}
	}
}
