// This file has been autogenerated from a class added in the UI designer.

using System;

namespace MonoDevelop.Inspector
{
    public interface IAccessibilityWindow : IWindow
	{
		event EventHandler<IView> RaiseAccessibilityIssueSelected;
		event EventHandler AuditRequested;
		event EventHandler ShowErrorsRequested;

		string IssuesLabel { get; set; }
	}
}
