// This file has been autogenerated from a class added in the UI designer.

using System;
namespace MonoDevelop.Inspector
{
    public interface IButton : INativeObject
    {
        event EventHandler Pressed;
        void SetTooltip(string v);
        void SetWidth(int v);
    }
}