// This file has been autogenerated from a class added in the UI designer.

namespace MonoDevelop.Inspector
{
    public interface IMenuWrapper : INativeObject
    {
        void InsertItem(IMenuItemWrapper item, int v);
    }

    public interface IMenuItemWrapper : INativeObject
    {
        void SetTitle(string v);
    }
}