// This file has been autogenerated from a class added in the UI designer.

namespace MonoDevelop.Inspector
{
    public interface IMenu : INativeObject
    {
        void InsertItem(IMenuItem item, int v);
    }

    public interface IMenuItem : INativeObject
    {
        void SetTitle(string v);
    }
}