// This file has been autogenerated from a class added in the UI designer.


namespace MonoDevelop.Inspector
{
    public interface ITab : INativeObject
    {
        public string NodeName { get; }
    }

    public interface ITabItem : INativeObject
    {
        public string NodeName { get; }
    }
}
