// This file has been autogenerated from a class added in the UI designer.

namespace MonoDevelop.Inspector
{
    public interface IColor : INativeObject
    {

    }
    public interface IFontWrapper : INativeObject
    {

    }
    public interface ITextBoxWrapper : IView
    {
        IColor BackgroundColor { get; set; }
        IColor TextColor { get; set; }
        IFontWrapper Font { get; set; }
    }
}
