// This file has been autogenerated from a class added in the UI designer.

using System.Collections.Generic;

namespace MonoDevelop.Inspector
{
    public interface IRectangle : INativeObject
    {

    }

    public enum InspectorViewMode
    {
        Native,
        Xwt
    }

    public interface IConstrain : INativeObject
    {
        string NodeName { get; }
        string Identifier { get; }
        IView PreviousValidKeyView { get; }
        void RemoveFromSuperview();
    }

    public interface IConstrainContainer : INativeObject
    {
        string NodeName { get; }
        IView PreviousValidKeyView { get; }
        void RemoveFromSuperview();
    }

    public interface IView
        : INativeObject
    {
		bool Hidden { get; }
		string Identifier { get; }
        IRectangle AccessibilityFrame { get; }
		List<IView> Subviews { get; }
		IView NextValidKeyView { get; }
		IView PreviousValidKeyView { get; }
        IRectangle Frame { get; }
		IView Superview { get; }
		string AccessibilityTitle { get; set; }
		string AccessibilityHelp { get; set; }
		object AccessibilityParent { get; set; }
		bool CanBecomeKeyView { get; }
		object View { get; }
		string NodeName { get; }
        bool HasConstraints { get; }
        List<IConstrain> Constraints { get; }

        void RemoveFromSuperview ();
        void Focus();
    }
}
