// This file has been autogenerated from a class added in the UI designer.

using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using CoreGraphics;
using MonoDevelop.Inspector;
using MonoDevelop.Inspector.Mac;
using ObjCRuntime;
using VisualStudio.ViewInspector;
using VisualStudio.ViewInspector.Abstractions;
using VisualStudio.ViewInspector.Mac.Views;

namespace AppKit
{
	public static class Extensions
	{
		public static bool IsLabel(this NSTextField nSTextField)
        {
			return !nSTextField.DrawsBackground && !nSTextField.Editable && !nSTextField.Bezeled;
		}

		internal static VisualStudio.ViewInspector.Mac.Abstractions.Color ToColor(this NSColor color)
			=> new VisualStudio.ViewInspector.Mac.Abstractions.Color(color);

	
		internal static VerticalSeparator AddVerticalSeparator(this NSStackView stack)
		{
			var separator = new VerticalSeparator();
			stack.AddArrangedSubview(separator);
			return separator;
		}

		public static bool IsBlockedType (this IView customView)
		{
			if (customView is NSTableViewCell)
			{
				return true;
			}
			return false;
		}

		public static PropertyInfo GetProperty(this object obj, string propertyName)
		{
			return obj.GetType().GetProperty(propertyName);
		}

		internal static TreeNode Search (this TreeNode nodeView, VisualStudio.ViewInspector.Abstractions.INativeObject view)
		{
			if (nodeView.Content != null && nodeView.Content.NativeObject == view.NativeObject) {
				return nodeView;
			}

			if (nodeView.ChildCount == 0) {
				return null;
			}

			for (int i = 0; i < nodeView.ChildCount; i++) {
				var node = (TreeNode) nodeView.GetChild (i);
				var found = Search (node, view);
				if (found != null) {
					return found;
				}
			}
			return null;
		}
		public static void AlignRight (this NSWindow sender, NSWindow toView, int pixels)
		{
			var frame = sender.Frame;
			frame.Location = new CGPoint(toView.Frame.Right + pixels, toView.Frame.Bottom - frame.Height);
			sender.SetFrame(frame, true);
		}

		public static void AlignLeft (this NSWindow sender, NSWindow toView, int pixels)
		{
			var frame = sender.Frame;
			frame.Location = new CGPoint(toView.Frame.Left - sender.Frame.Width - pixels, toView.Frame.Bottom - frame.Height);
			sender.SetFrame(frame, true);
		}

		public static void AlignTop (this NSWindow from, NSWindow toView, int pixels)
		{
			var frame = from.Frame;
			frame.Location = new CGPoint(toView.Frame.Left, toView.AccessibilityFrame.Y + toView.Frame.Height + pixels);
			from.SetFrame(frame, true);
		}

		public static CGRect Add (this CGRect sender, CGRect toAdd)
		{
			return new CGRect (sender.X + toAdd.X, sender.Y + toAdd.Y, sender.Width + toAdd.Width, sender.Height + toAdd.Height);
		}

		public static CGRect Add (this CGRect sender, CGPoint toAdd)
		{
			return new CGRect (sender.X + toAdd.X, sender.Y + toAdd.Y, sender.Width, sender.Height);
		}

		public static CGRect Add (this CGRect sender, CGSize toAdd)
		{
			return new CGRect (sender.X, sender.Y, sender.Width + toAdd.Width, sender.Height + toAdd.Height);
		}
	}
}
