// This file has been autogenerated from a class added in the UI designer.

using AppKit;
using CoreGraphics;
using MonoDevelop.Inspector.Mac;
using System;
using VisualStudio;

namespace VisualStudio.ViewInspector
{
    public static class Runtime
    {
        public static void Initialize(bool hasToolkit = false)
        {
            var inspectorDelegate = new MacInspectorDelegate();
            var inspectorManager = inspectorDelegate.CreateInspectorManager();
            InspectorContext.Current.Initialize(inspectorDelegate, inspectorManager, hasToolkit);
            InspectorContext.Current.StartWatcher();
        }
    }
}
