// This file has been autogenerated from a class added in the UI designer.

namespace MonoDevelop.Inspector
{
	public class ColorResult
	{
		public IView View {
			get;
			set;
		}
		public IColor Color {
			get;
			set;
		}
	}
}
