// This file has been autogenerated from a class added in the UI designer.

using AppKit;
using CoreGraphics;

namespace MonoDevelop.Inspector.Mac
{
	internal class MacInspectorContext : InspectorContext
	{
		public MacInspectorContext ()
		{

		}

		IInspectDelegate macDelegate;
		public virtual IInspectDelegate GetInspectorDelegate ()
		{
			if (macDelegate == null)
				macDelegate = new MacInspectorDelegate ();
			return macDelegate;
		}

		protected override InspectorManager GetInitializationContext ()
		{
			var inspectorDelegate = GetInspectorDelegate ();
			var over = new MacBorderedWindow (CGRect.Empty, NSColor.Green);
			var next = new MacBorderedWindow (CGRect.Empty, NSColor.Red);
			var previous = new MacBorderedWindow (CGRect.Empty, NSColor.Blue);
			var acc = new MacAccessibilityWindow (new CGRect (10, 10, 600, 700));
			var ins = new InspectorWindow (inspectorDelegate, new CGRect (10, 10, 600, 700)); ;
			var tool = new MacToolbarWindow (inspectorDelegate, new CGRect (10, 10, 100, 700));
			tool.ShowToolkit (hasToolkit);

			return new InspectorManager (macDelegate, over, next, previous, acc, ins, tool);
		}

		public static MacInspectorContext Current { get; set; } = new MacInspectorContext ();
	}
}
