// This file has been autogenerated from a class added in the UI designer.

using AppKit;
using CoreGraphics;

namespace MonoDevelop.Inspector.Mac
{
	internal class MacInspectorContext : InspectorContext
	{
		public MacInspectorContext ()
		{

		}

		IInspectDelegate macDelegate;
		public virtual IInspectDelegate GetInspectorDelegate ()
		{
			if (macDelegate == null)
				macDelegate = new MacInspectorDelegate ();
			return macDelegate;
		}

		protected override InspectorManager GetInitializationContext ()
		{
			var inspectorDelegate = GetInspectorDelegate ();
			var overlayWindow = new BorderedWindow (CGRect.Empty, NSColor.Green);
			var nextWindow = new BorderedWindow (CGRect.Empty, NSColor.Red);
			var previousWindow = new BorderedWindow (CGRect.Empty, NSColor.Blue);
			var accWindow = new AccessibilityToolWindow (new CGRect (10, 10, 600, 700));
			var inspectorWindow = new InspectorToolWindow (inspectorDelegate, new CGRect (10, 10, 600, 700)); ;
			var macToolbar = new ToolbarWindow (inspectorDelegate, new CGRect (10, 10, 100, 700));
			macToolbar.ShowToolkit (hasToolkit);

			return new InspectorManager (macDelegate, overlayWindow, nextWindow, previousWindow, accWindow, inspectorWindow, macToolbar);
		}

		public static MacInspectorContext Current { get; set; } = new MacInspectorContext ();
	}
}
