// This file has been autogenerated from a class added in the UI designer.

using AppKit;

namespace MonoDevelop.Inspector.Mac
{
    class MacMenuItemWrapper : IMenuItemWrapper
    {
        private NSMenuItem submenu;

        public MacMenuItemWrapper(NSMenuItem submenu)
        {
            this.submenu = submenu;
        }

        public void SetTitle(string title)
        {
            submenu.Title = title;
        }

        public object NativeObject => submenu;
    }
}
