// This file has been autogenerated from a class added in the UI designer.

using System;
using VisualStudio.ViewInspector.Abstractions;

namespace VisualStudio.ViewInspector
{
	public class FontData
	{
		public IFont Font { get; private set; }
		public float Size { get; private set; }

		public FontData (IFont font, float size)
		{
			this.Font = font;
			Size = size;
		}
	}
}
