// This file has been autogenerated from a class added in the UI designer.


using System.Collections.Generic;
using VisualStudio.ViewInspector.Modules;

namespace VisualStudio.ViewInspector
{
    public interface IInspectorContextDelegate
    {
        IInspectDelegate GetInspectorDelegate();
        object GetInspectorManager(List<IInspectorTabModule> modules);
    }
}
