// This file has been autogenerated from a class added in the UI designer.

using AppKit;
using CoreGraphics;

namespace VisualStudio.ViewInspector.Mac.Windows.Toolbar
{
    class ColorWell : NSColorWell
	{
		public override CGSize IntrinsicContentSize => new CGSize(50, 21);

		public ColorWell()
		{
			TranslatesAutoresizingMaskIntoConstraints = false;
		}
	}
}
