// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using AppKit;
using MonoDevelop.Inspector.Mac.HostWindow;
using MonoDevelop.Inspector.Mac.TouchBar;

namespace MonoDevelop.Inspector.Mac.Services
{
    class ToolbarService
    {
        readonly Dictionary<Type, TouchBarBaseDelegate> dicctionary = new Dictionary<Type, TouchBarBaseDelegate>();

        IInspectDelegate inspectorDelegate;
        public void SetDelegate (IInspectDelegate inspectorDelegate)
        {
            this.inspectorDelegate = inspectorDelegate;
        }

        public TouchBarBaseDelegate GetTouchBarDelegate(object element)
        {
            return dicctionary[typeof(NSView)];
        }

        public ToolbarService()
        {
            var colorPickerDelegate = new ColorPickerDelegate();
            dicctionary.Add(typeof(NSView), colorPickerDelegate);
        }

        public static ToolbarService Current = new ToolbarService();
    }
}
