// This file has been autogenerated from a class added in the UI designer.

using AppKit;

namespace MonoDevelop.Mac.Debug.Services
{
	public class ColorResult
	{
		public IViewWrapper View {
			get;
			set;
		}
		public NSColor Color {
			get;
			set;
		}
	}
}
