// This file has been autogenerated from a class added in the UI designer.

using AppKit;

namespace MonoDevelop.Mac.Debug.Services
{
	public interface ITextBoxWrapper : IViewWrapper
	{
		NSColor BackgroundColor { get; set; }
		NSColor TextColor { get; set; }
		NSFont Font { get; set; }
	}
}
