// This file has been autogenerated from a class added in the UI designer.


namespace MonoDevelop.Inspector
{
    public interface IInspectorTabModule
    {
        bool IsEnabled { get; }
        void Load (ITabWrapper tab);
    }
}
