// This file has been autogenerated from a class added in the UI designer.

using VisualStudio.ViewInspector.Abstractions;

namespace VisualStudio.ViewInspector.Services
{
	public class ColorResult
	{
		public IView View {
			get;
			set;
		}
		public IColor Color {
			get;
			set;
		}
	}
}
