// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MonoDevelop.Mac.Debug;

namespace DebugExample
{
	public partial class MainWindow : DebugWindow
	{
		public MainWindow (IntPtr handle) : base (handle)
		{
			SetMenu(Menu);
		}
	}
}
