// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;

namespace MonoDevelop.Mac.Debug
{
	public class FontData
	{
		readonly static public nfloat DefaultSize = NSFont.SystemFontSize;
		readonly static public NSFont DefaultFont = NSFont.FromFontName (DefaultFontName, DefaultSize);

		public const string DefaultFontName = ".AppleSystemUIFont";

		public NSFont Font { get; private set; }
		public nfloat Size { get; private set; }

		public FontData (string font, nfloat size)
		{
			Size = size;
			Font = NSFont.FromFontName (font, size);
		}

		public FontData (NSFont font, nfloat size)
		{
			this.Font = font;
			Size = size;
		}
	}
}
