// This file has been autogenerated from a class added in the UI designer.

using System;

namespace MonoDevelop.Mac.Debug
{
	public interface IAccessibilityWindow : IWindowWrapper
	{
		event EventHandler<IViewWrapper> RaiseAccessibilityIssueSelected;
		event EventHandler AuditRequested;
		event EventHandler ShowErrorsRequested;

		string IssuesLabel { get; set; }


	}
}
