// This file has been autogenerated from a class added in the UI designer.

using System;

namespace MonoDevelop.Mac.Debug
{
	public interface IToolbarWindow : IWindowWrapper
	{
		event EventHandler<bool> KeyViewLoop;
		event EventHandler<bool> NextKeyViewLoop;
		event EventHandler<bool> PreviousKeyViewLoop;
		event EventHandler<bool> ThemeChanged;
		event EventHandler ItemDeleted;
		event EventHandler ItemImageChanged;
		event EventHandler<FontData> FontChanged;
		event EventHandler<InspectorViewMode> InspectorViewModeChanged;
		bool ImageChangedEnabled { get; set; }
	}
}
