// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;

namespace MonoDevelop.Mac.Debug
{
	class ToolbarWindow : NSWindow
	{
		public event EventHandler<bool> KeyViewLoop;
		public event EventHandler<bool> NextKeyViewLoop;
		public event EventHandler<bool> PreviousKeyViewLoop;

		public event EventHandler<bool> ThemeChanged;

		public event EventHandler ItemDeleted;
		public event EventHandler ItemImageChanged;

		const int MenuItemSeparation = 3;
		const int LeftPadding = 5;

		readonly NSStackView stackView;

		public ToolbarWindow ()
		{
			//BackgroundColor = NSColor.Clear;
			IsOpaque = false;
			StyleMask = NSWindowStyle.Titled | NSWindowStyle.FullSizeContentView;
			TitlebarAppearsTransparent = true;
			TitleVisibility = NSWindowTitleVisibility.Hidden;
			ShowsToolbarButton = false;
			MovableByWindowBackground = false;

			stackView = NativeViewHelper.CreateHorizontalStackView (MenuItemSeparation);
			ContentView.AddSubview (stackView);
			stackView.CenterYAnchor.ConstraintEqualToAnchor (ContentView.CenterYAnchor, 0).Active = true;
			stackView.LeftAnchor.ConstraintEqualToAnchor (ContentView.LeftAnchor, LeftPadding).Active = true;

			//Visual issues view
			var keyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-actual"));
			AddButton (keyViewLoopButton);
			keyViewLoopButton.Activated += (s, e) => {
				KeyViewLoop?.Invoke(this, keyViewLoopButton.IsToggled);
			};

			var prevKeyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-previous"));
			AddButton (prevKeyViewLoopButton);
			prevKeyViewLoopButton.Activated += (s, e) => {
				PreviousKeyViewLoop?.Invoke(this, prevKeyViewLoopButton.IsToggled);
			};

			var nextKeyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-next"));
			AddButton (nextKeyViewLoopButton);
			nextKeyViewLoopButton.Activated += (s, e) => {
				NextKeyViewLoop?.Invoke(this, nextKeyViewLoopButton.IsToggled);
			};

			AddSeparator ();

			var themeButton = new ToggleButton (NSImage.ImageNamed ("style-16"));
			AddButton (themeButton);
			themeButton.Activated += ThemeButton_Activated;

			AddSeparator ();

			deleteButton = new ImageButton(NSImage.ImageNamed("delete-16"));

			AddButton(deleteButton);
			deleteButton.Activated += (s,e) =>
			{
				ItemDeleted?.Invoke(this, EventArgs.Empty);
			};

			changeImage = new ImageButton(NSImage.ImageNamed("image-16"));

			AddButton(changeImage);
			changeImage.Activated += (s, e) =>
			{
				ItemImageChanged?.Invoke(this, EventArgs.Empty);
			};

			AddSeparator();
		}

		public override bool CanBecomeKeyWindow => false;
		public override bool CanBecomeMainWindow => false;

		ImageButton deleteButton, changeImage;

		public bool DeleteEnabled
		{
			get => deleteButton.Enabled;
			set => deleteButton.Enabled = value;
		}

		public bool ImageChangedEnabled
		{
			get => changeImage.Enabled;
			set => changeImage.Enabled = value;
		}

		void ThemeButton_Activated (object sender, EventArgs e)
		{
			if (sender is ToggleButton btn) {
				ThemeChanged?.Invoke (this, btn.IsToggled);
			}
		}

		void AddSeparator () => stackView.AddArrangedSubview (new VerticalSeparator ());

		void AddButton (NSButton view)
		{
			stackView.AddArrangedSubview (view);
			view.WidthAnchor.ConstraintEqualToConstant (InspectorWindow.ButtonWidth).Active = true;
		}

		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
	}
}
