// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;
using Xamarin.PropertyEditing.Mac;
using Xamarin.PropertyEditing.Themes;
using MonoDevelop.Mac.Debug.Services;

namespace MonoDevelop.Mac.Debug
{
	class ToolbarWindow : NSWindow
	{
		public event EventHandler ShowIssues;
		public event EventHandler ScanForIssues;

		public event EventHandler<bool> KeyViewLoop;
		public event EventHandler<bool> NextKeyViewLoop;
		public event EventHandler<bool> PreviousKeyViewLoop;

		public event EventHandler<bool> ThemeChanged;

		const int MenuItemSeparation = 3;
		const int LeftPadding = 5;

		NSButton errorTextButton;
		NSTextField errorLabel;

		readonly NSStackView stackView;

		public ToolbarWindow ()
		{
			//BackgroundColor = NSColor.Clear;
			IsOpaque = false;
			StyleMask = NSWindowStyle.Titled | NSWindowStyle.FullSizeContentView;
			TitlebarAppearsTransparent = true;
			TitleVisibility = NSWindowTitleVisibility.Hidden;
			ShowsToolbarButton = false;
			MovableByWindowBackground = false;

			stackView = NativeViewHelpers.CreateHorizontalStackView (MenuItemSeparation);
			ContentView.AddSubview (stackView);
			stackView.CenterYAnchor.ConstraintEqualToAnchor (ContentView.CenterYAnchor, 0).Active = true;
			stackView.LeftAnchor.ConstraintEqualToAnchor (ContentView.LeftAnchor, LeftPadding).Active = true;

			//Visual issues view
			var keyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-actual"));
			AddButton (keyViewLoopButton);
			keyViewLoopButton.Activated += (s, e) => {
				KeyViewLoop?.Invoke(this, keyViewLoopButton.IsToggled);
			};

			var prevKeyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-previous"));
			AddButton (prevKeyViewLoopButton);
			prevKeyViewLoopButton.Activated += (s, e) => {
				PreviousKeyViewLoop?.Invoke(this, prevKeyViewLoopButton.IsToggled);
			};

			var nextKeyViewLoopButton = new ToggleButton(NSImage.ImageNamed("overlay-next"));
			AddButton (nextKeyViewLoopButton);
			nextKeyViewLoopButton.Activated += (s, e) => {
				NextKeyViewLoop?.Invoke(this, nextKeyViewLoopButton.IsToggled);
			};

			AddSeparator ();

			var themeButton = new ToggleButton (NSImage.ImageNamed ("style-16"));
			AddButton (themeButton);
			themeButton.Activated += ThemeButton_Activated;

			AddSeparator ();

			errorTextButton = new ToggleButton (NSImage.ImageNamed("error-16"));
			AddButton (errorTextButton);
			errorTextButton.Activated += ErrorTextButton_Activated;

			var rescanButton = new ImageButton(NSImage.ImageNamed("rescan-16"));
			AddButton (rescanButton);
			rescanButton.Activated += RescanButton_Activated;

			AddSeparator ();

			errorLabel = NativeViewHelpers.CreateLabel ("");
			stackView.AddArrangedSubview(errorLabel);

			var accessibilityService = AccessibilityService.Current;
			accessibilityService.ScanFinished += (s, e) =>
			{
				errorLabel.StringValue = string.Format ("{0} errors found.", accessibilityService.IssuesFound);
			};
		}

		public string IssuesLabel {
			get => errorLabel.StringValue;
			set => errorLabel.StringValue = value;
		}

		void ThemeButton_Activated (object sender, EventArgs e)
		{
			if (sender is ToggleButton btn) {
				ThemeChanged?.Invoke (this, btn.IsToggled);
			}
		}

		void AddSeparator () => stackView.AddArrangedSubview (new VerticalSeparator ());

		void AddButton (NSButton view)
		{
			stackView.AddArrangedSubview (view);
			view.WidthAnchor.ConstraintEqualToConstant (InspectorWindow.ButtonWidth).Active = true;
		}

		void RescanButton_Activated(object sender, EventArgs e)
		{
			ScanForIssues?.Invoke(this, EventArgs.Empty);
		}

		void ErrorTextButton_Activated(object sender, EventArgs e)
		{
			ShowIssues?.Invoke(this, EventArgs.Empty);
		}

		protected override void Dispose(bool disposing)
		{
			errorTextButton.Activated -= ErrorTextButton_Activated;
			base.Dispose(disposing);
		
		}
	}
}
