// This file has been autogenerated from a class added in the UI designer.

using System;

namespace MonoDevelop.Inspector
{
	public class FontData
	{
		
		public IFontWrapper Font { get; private set; }
		public float Size { get; private set; }

		

		public FontData (IFontWrapper font, float size)
		{
			this.Font = font;
			Size = size;
		}
	}
}
