// This file has been autogenerated from a class added in the UI designer.


namespace MonoDevelop.Inspector
{
    public interface IBorderedWindow : IWindowWrapper
    {
        float BorderWidth { get; set; }
        bool Visible { get; set; }
        void SetParentWindow(IWindowWrapper selectedWindow);
        void AlignWith(IViewWrapper view);
        void AlignWindowWithContentView();
        void OrderFront();
    }
}
