// This file has been autogenerated from a class added in the UI designer.


using System.Collections.Generic;

namespace MonoDevelop.Inspector
{
    public interface IInspectorContextDelegate
    {
        IInspectDelegate GetInspectorDelegate();
        object GetInspectorManager(List<IInspectorTabModule> modules);
    }
}
