// This file has been autogenerated from a class added in the UI designer.


namespace MonoDevelop.Inspector
{
    public interface INodeView : INativeObject
    {
        void AddChild(INodeView nodel);
    }
}