// This file has been autogenerated from a class added in the UI designer.

namespace MonoDevelop.Inspector
{
    public interface IColorWrapper : INativeObject
    {

    }
    public interface IFontWrapper : INativeObject
    {

    }
    public interface ITextBoxWrapper : IViewWrapper
    {
        IColorWrapper BackgroundColor { get; set; }
        IColorWrapper TextColor { get; set; }
        IFontWrapper Font { get; set; }
    }
}
