// This file has been autogenerated from a class added in the UI designer.

using System;

namespace MonoDevelop.Inspector
{
    public interface IToolbarWrapperDelegateWrapper : INativeObject
    {

    }

    interface IToolbarWindow : IWindowWrapper
	{
        void ShowToolkit(bool value);
        event EventHandler<bool> KeyViewLoop;
		event EventHandler<bool> NextKeyViewLoop;
		event EventHandler<bool> PreviousKeyViewLoop;
		event EventHandler<bool> ThemeChanged;
		event EventHandler ItemDeleted;
		event EventHandler ItemImageChanged;
		event EventHandler<FontData> FontChanged;
		event EventHandler<InspectorViewMode> InspectorViewModeChanged;
		bool ImageChangedEnabled { get; set; }
        void ChangeView(InspectorManager manager, IViewWrapper viewWrapper);
    }
}
