// This file has been autogenerated from a class added in the UI designer.


using AppKit;

namespace MonoDevelop.Inspector.Mac
{
	class ImageButton : NSButton
	{
		public bool BecomeKeyView = true;

		public override bool CanBecomeKeyView => BecomeKeyView;

		public ImageButton()
		{
			Bordered = true;
			BezelStyle = NSBezelStyle.Rounded;
			Title = "";
			BecomeKeyView = false;
			ImageScaling = NSImageScale.AxesIndependently;
			TranslatesAutoresizingMaskIntoConstraints = false;
		}

		public bool Visible {
			get => !Hidden;
			set => Hidden = !value;
		}
	}
}
