// This file has been autogenerated from a class added in the UI designer.


namespace VisualStudio.ViewInspector.Abstractions
{
    public interface IBorderedWindow : IWindow
    {
        float BorderWidth { get; set; }
        bool Visible { get; set; }
        void SetParentWindow(IWindow selectedWindow);
        void AlignWith(IView view);
        void AlignWindowWithContentView();
        void OrderFront();
    }
}
