// This file has been autogenerated from a class added in the UI designer.


namespace VisualStudio.ViewInspector.Abstractions
{
    public interface INativeObject
    {
        object NativeObject { get; }
    }
}