// This file has been autogenerated from a class added in the UI designer.


namespace VisualStudio.ViewInspector.Abstractions
{
    public interface INodeView : INativeObject
    {
        void AddChild(INodeView nodel);
    }
}