// This file has been autogenerated from a class added in the UI designer.

namespace VisualStudio.ViewInspector.Abstractions
{
    public interface IColor : INativeObject
    {

    }
    public interface IFont : INativeObject
    {

    }
    public interface ITextBoxWrapper : IView
    {
        IColor BackgroundColor { get; set; }
        IColor TextColor { get; set; }
        IFont Font { get; set; }
    }
}
